server:
  port: 80

spring:
  # H2 Database
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:test
      username: sa
      password:

  # H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console

  # H2 Schema
  sql:
    init:
      schema-locations: classpath*:db/h2/member.sql

  # JPA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
